name: untitled
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  auto_route: ^7.9.0
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  connectivity_plus: ^5.0.1
  dart_jsonwebtoken: ^2.11.0
  dio: ^5.2.1+1
  easy_localization: ^3.0.7

  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.1
  flutter_screenutil: ^5.8.1
  fluttertoast: ^8.2.6
  get_it: ^7.7.0
  hooks_riverpod: ^2.5.1
  json_annotation: ^4.9.0
  retrofit: ^4.1.0
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.3
  mockito: ^5.4.4



dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  flutter_flavorizr: ^2.1.6
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.4
  riverpod_generator: ^2.3.11

flutter:
  uses-material-design: true
  assets:
    - assets/images/


  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700